server:
  port: 8080
  session: 
    timeout: 10
  tomcat: 
    uri-encoding: UTF-8

spring:
  profiles: dev
  datasource: 
    url: jdbc:mysql://njfhoddiowm4yjdj.dev.mysql.saybot.net:3306/love_dubbing
    username: love_dubbing
    password: OGZmZjdlZjg4M2Jk
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa: 
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  redis:
    host: njfhoddiowm4yjdj.dev.redis.saybot.net
    port: 6379
    password: 
    pool:  
      max-active: 8  
      max-idle: 8  
      min-idle: 0  
      max-wait: -1
    timeout: 0  